backend/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib import admin

from . import views

app_name = 'backend'
urlpatterns = [
    path('', views.admin, name='admin'),

    path('categories/', views.category_list, name='category_list'),
    path('categories/new/', views.category_new, name='category_new'),
    path('categories/add/', views.category_add, name='category_add'),
    path('categories/<int:category_id>/', views.category_details, name='category_details'),
    path('categories/<int:category_id>/edit/', views.category_edit, name='category_edit'),
    path('categories/<int:category_id>/delete/', views.category_delete, name='category_delete'),

    path('e/', views.event_list, name='event_list'),
    path('e/new/', views.event_new, name='event_new'),
    path('e/add/', views.event_add, name='event_add'),
    path('e/<int:event_id>/dashboard', views.event_dashboard, name='event_dashboard'),
    path('e/<int:event_id>/publish', views.event_publish_button, name='event_publish_button'),
    path('e/<int:event_id>/', views.event_details, name='event_details'),
    path('e/<int:event_id>/edit/', views.event_edit, name='event_edit'),
    path('e/<int:event_id>/delete/', views.event_delete, name='event_delete'),

    path('e/<int:event_id>/t/', views.ticket_list, name='ticket_list'),
    path('e/<int:event_id>/t/new/', views.ticket_new, name='ticket_new'),
    path('e/<int:event_id>/t/add/', views.ticket_add, name='ticket_add'),
    path('e/<int:event_id>/t/<int:ticket_id>/', views.ticket_details, name='ticket_details'),
    path('e/<int:event_id>/t/<int:ticket_id>/edit/', views.ticket_edit, name='ticket_edit'),
    path('e/<int:event_id>/t/<int:ticket_id>/delete/', views.ticket_delete, name='ticket_delete'),

    path('e/<int:event_id>/attendees/', views.attendee_list, name='attendee_list'),
    path('e/<int:event_id>/attendees/download/', views.attendee_download, name='attendee_download'),
    path('e/<int:event_id>/attendees/download-addons/', views.attendee_download_addon, name='attendee_download_addon'),
    path('e/<int:event_id>/orders/', views.order_list, name='order_list'),
    path('e/<int:event_id>/orders/download/', views.order_download, name='order_download'),
    path('e/<int:event_id>/stats/', views.stat_show, name='stat_show'),
    path('e/<int:event_id>/stats/location-download', views.stat_location_download, name='stat_location_download'),
    path('e/<int:event_id>/stats/date-ticket-download', views.stat_date_ticket_download, name='stat_date_ticket_download'),
    path('e/<int:event_id>/stats/date-addon-download', views.stat_date_addon_download, name='stat_date_addon_download'),
    path('e/<int:event_id>/stats/revenue-download', views.stat_revenue_download, name='stat_revenue_download'),
]

event_ticket_py/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frontend.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', include('backend.urls')),
    path('django-admin/', admin.site.urls), # comment this out when doing custom user migrations the first time
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.postgres.fields import *
from event_ticket_py import settings

from psycopg2.extras import DateTimeTZRange
from django.core.validators import *

from backend.validators import *

from django.utils import timezone

from django import forms

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)
    path = models.CharField(max_length=30, null=False, validators=[validate_unicode_slug])
    description = models.TextField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = "categories"
    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)
    path = models.CharField(max_length=60, null=False, validators=[validate_unicode_slug])
    description = models.TextField(blank=True, null=True)
    venue_name = models.CharField(max_length=100, blank=False, null=False)
    venue_address = models.CharField(max_length=100, blank=False, null=False)
    class Refunds(models.IntegerChoices):
        ONE_DAY = 1
        ONE_WEEK = 2
        ONE_MONTH = 3
        NO_REFUNDS = 4
        NOT_DEFINED = 5
    refunds = models.IntegerField(choices=Refunds.choices, default=Refunds.NOT_DEFINED, null=False)
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    is_published = models.BooleanField(default=False)
    is_hidden = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    banner = models.ImageField(upload_to=user_directory_path, blank=True, null=True, validators=[file_size])

    class Meta:
        unique_together = ['path', 'user']

    def __str__(self):
        return self.name

class Ticket(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)
    path = models.CharField(max_length=60, null=False, validators=[validate_unicode_slug])
    description = models.TextField(blank=True, null=True)
    for_sale_date_start = models.DateTimeField(blank=False, null=False)
    for_sale_date_end = models.DateTimeField(blank=False, null=False)
    is_hidden = models.BooleanField(default=False)
    class TicketType(models.IntegerChoices):
        TICKET = 1
        EXTRA = 2
    ticket_type = models.IntegerField(choices=TicketType.choices, blank=False)
    quantity = models.IntegerField(blank=False, null=False)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['path', 'event']
    
    def __str__(self):
        return "(id: " + str(self.id) + ") " + self.name
    
class Order(models.Model):
    first_name = models.CharField(max_length=200, blank=False, null=False)
    last_name = models.CharField(max_length=200, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True)
    credit_last_four = models.CharField(max_length=4, default="0003", blank=False, null=False, validators=[MinLengthValidator(4), MaxLengthValidator(4)])
    address_one = models.CharField(max_length=200, blank=False, null=False)
    address_two = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=False, null=False)
    province = models.CharField(max_length=200, blank=False, null=False)
    country = models.CharField(max_length=200, blank=False, null=False)
    order_total = models.DecimalField(max_digits=10, decimal_places=2)
    refunded_amount = models.DecimalField(max_digits=9, decimal_places=2, default=0, blank=True, null=False)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, blank=True, null=False)
    class Status(models.IntegerChoices):
        PENDING = 1
        COMPLETE = 2
        REFUNDED = 3
    status = models.IntegerField(choices=Status.choices, blank=False)
    def __str__(self):
        return self.first_name + " ($" + str(self.order_total) + ")" + " - " + self.date.strftime('%Y-%m-%d %H:%M') + " UTC"

class TicketOrder(models.Model):
    first_name = models.CharField(max_length=200, blank=False, null=True)
    last_name = models.CharField(max_length=200, blank=False, null=True)
    email = models.EmailField(blank=False, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=False)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, blank=True, null=False, related_name='ticketorder')
    class Status(models.IntegerChoices):
        PENDING = 1
        COMPLETE = 2
        REFUNDED = 3
    status = models.IntegerField(choices=Status.choices, blank=False)
    def __str__(self):
        ticket_name = self.ticket.name
        return str(self.order.id) + " " + self.order.first_name + " " + self.order.last_name + " - " + ticket_name

class Cart(models.Model):
    code = models.CharField(max_length=36)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, blank=False, null=False)
    quantity = models.IntegerField(blank=False, null=False, default=0)
    price = models.IntegerField(blank=False, null=False, default=0)
    def __str__(self):
        return str(self.code) + " - " + self.ticket.name + " / " + self.ticket.event.name

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'path', 'description']

class EventFormCreate(ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'path', 'description', 'banner', 'venue_name', 'venue_address', 'refunds', 'is_hidden', 'date_start', 'date_end', 'category']
        labels = {
            'is_hidden': 'Should event be hidden?'
        }
        widgets = {
            'date_start': forms.TextInput(attrs={'class': "date-picker"}),
            'date_end': forms.TextInput(attrs={'class': "date-picker"}),
        }

class EventFormEdit(ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'path', 'description', 'banner', 'venue_name', 'venue_address', 'refunds', 'date_start', 'date_end', 'is_hidden', 'category', 'is_published']
        labels = {
            'is_hidden': 'Should event be hidden?'
        }
        widgets = {
            'date_start': forms.TextInput(attrs={'class': "date-picker"}),
            'date_end': forms.TextInput(attrs={'class': "date-picker"}),
        }

class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ['name', 'path', 'description', 'for_sale_date_start', 'for_sale_date_end', 'is_hidden', 'ticket_type', 'quantity', 'price']
        labels = {
            'date': 'Date displayed on ticket'
        }
        widgets = {
            'for_sale_date_start': forms.TextInput(attrs={'class': "date-picker"}),
            'for_sale_date_end': forms.TextInput(attrs={'class': "date-picker"}),
        }

class TicketOrderForm(ModelForm):
    class Meta:
        model = TicketOrder
        fields = ['first_name', 'last_name', 'email', 'ticket']
        widgets = {
            'ticket': forms.HiddenInput(),
        }

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address_one', 'address_two', 'city', 'province', 'country']

backend/templates/backend/ticket/details.html
{% extends 'base_backend.html' %}
{% load static %}

{% block title %}Edit Ticket{% endblock %}

{% block body_class %}two-navs{% endblock %}

{% block navigation_secondary %}
    {% include "nav_events.html" with event_id=event.id %}
{% endblock %}

{% block content %}

<div class="heading">
    <h1>Edit Ticket</h1>
</div>

<form class="box" method="post" action="{% url 'backend:ticket_edit' event.id ticket.id %}">
    <table cellpadding="0">{{ form.as_table }}</table>
    <input type="submit" value="Save">
    {% csrf_token %}
</form>
{% endblock %}

{% block scripts %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script type="text/javascript" src="{% static 'backend/datetime_picker.js' %}"></script>
<script type="text/javascript" src="{% static 'backend/auto_copy_to_path.js' %}"></script>
{% endblock %}

backend/templates/backend/ticket/list.html
{% extends 'base_backend.html' %}

{% block title %}Tickets{% endblock %}

{% block body_class %}two-navs{% endblock %}

{% block navigation_secondary %}
    {% include "nav_events.html" with event_id=event.id %}
{% endblock %}

{% block content %}

<div class="heading">
    <h1>Tickets</h1>
    <a class="button" href="{% url 'backend:ticket_new' event.id %}">Add Ticket</a>
</div>

{% if all_tickets_list_with_count %}
    <div id="flex_container">
    {% for ticket in all_tickets_list_with_count %}
        <div class="ticket box flex-item">
            <p><strong>{{ ticket.name }}</strong> <span>({{ ticket.count }}/{{ ticket.quantity }} sold)</span>{% if ticket.is_hidden %} <span>(hidden)</span>{% endif %}</p>
            <p>Type: {{ ticket.get_ticket_type_display }}</p>
            <p>On sale date: {{ ticket.for_sale_date_start }}</p>
            <p>End sale date: {{ ticket.for_sale_date_end }}</p>
            <ul class="links">
                <li class="edit"><a href="{% url 'backend:ticket_details' event.id ticket.id %}">Edit</a></li>
                <li class="delete"><a href="{% url 'backend:ticket_delete' event.id ticket.id %}">Delete</a></li>
            </ul>
        </div>
    {% endfor %}
    </div>
{% else %}
    <p>No tickets are available.</p>
{% endif %}

{% endblock %}

backend/templates/backend/ticket/new.html
{% extends 'base_backend.html' %}
{% load static %}

{% block title %}Add Ticket{% endblock %}

{% block body_class %}two-navs{% endblock %}

{% block navigation_secondary %}
    {% include "nav_events.html" with event_id=event.id %}
{% endblock %}

{% block content %}

<div class="heading">
    <h1>Add Ticket</h1>
</div>

<form class="box" method="post" action="{% url 'backend:ticket_add' event.id %}">
    <table cellpadding="0">{{ form.as_table }}</table>
    <input type="submit" value="Save">
    {% csrf_token %}
</form>
{% endblock %}

{% block scripts %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script type="text/javascript" src="{% static 'backend/datetime_picker.js' %}"></script>
<script type="text/javascript" src="{% static 'backend/auto_copy_to_path.js' %}"></script>
{% endblock %}