backend/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib import admin

from . import views

app_name = 'backend'
urlpatterns = [
    path('', views.admin, name='admin'),

    path('categories/', views.category_list, name='category_list'),
    path('categories/new/', views.category_new, name='category_new'),
    path('categories/add/', views.category_add, name='category_add'),
    path('categories/<int:category_id>/', views.category_details, name='category_details'),
    path('categories/<int:category_id>/edit/', views.category_edit, name='category_edit'),
    path('categories/<int:category_id>/delete/', views.category_delete, name='category_delete'),

    path('e/', views.event_list, name='event_list'),
    path('e/new/', views.event_new, name='event_new'),
    path('e/add/', views.event_add, name='event_add'),
    path('e/<int:event_id>/dashboard', views.event_dashboard, name='event_dashboard'),
    path('e/<int:event_id>/publish', views.event_publish_button, name='event_publish_button'),
    path('e/<int:event_id>/', views.event_details, name='event_details'),
    path('e/<int:event_id>/edit/', views.event_edit, name='event_edit'),
    path('e/<int:event_id>/delete/', views.event_delete, name='event_delete'),

    path('e/<int:event_id>/t/', views.ticket_list, name='ticket_list'),
    path('e/<int:event_id>/t/new/', views.ticket_new, name='ticket_new'),
    path('e/<int:event_id>/t/add/', views.ticket_add, name='ticket_add'),
    path('e/<int:event_id>/t/<int:ticket_id>/', views.ticket_details, name='ticket_details'),
    path('e/<int:event_id>/t/<int:ticket_id>/edit/', views.ticket_edit, name='ticket_edit'),
    path('e/<int:event_id>/t/<int:ticket_id>/delete/', views.ticket_delete, name='ticket_delete'),

    path('e/<int:event_id>/attendees/', views.attendee_list, name='attendee_list'),
    path('e/<int:event_id>/attendees/download/', views.attendee_download, name='attendee_download'),
    path('e/<int:event_id>/attendees/download-addons/', views.attendee_download_addon, name='attendee_download_addon'),
    path('e/<int:event_id>/orders/', views.order_list, name='order_list'),
    path('e/<int:event_id>/orders/download/', views.order_download, name='order_download'),
    path('e/<int:event_id>/stats/', views.stat_show, name='stat_show'),
    path('e/<int:event_id>/stats/location-download', views.stat_location_download, name='stat_location_download'),
    path('e/<int:event_id>/stats/date-ticket-download', views.stat_date_ticket_download, name='stat_date_ticket_download'),
    path('e/<int:event_id>/stats/date-addon-download', views.stat_date_addon_download, name='stat_date_addon_download'),
    path('e/<int:event_id>/stats/revenue-download', views.stat_revenue_download, name='stat_revenue_download'),
]

event_ticket_py/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frontend.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', include('backend.urls')),
    path('django-admin/', admin.site.urls), # comment this out when doing custom user migrations the first time
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib import admin

from . import views
from frontend.views import SignUpView

app_name = 'frontend'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('o/<str:org_path>/', views.org, name='org'),
    path('o/<str:org_path>/<int:event_id>/', views.event, name='event'),
    path('o/<str:org_path>/<int:event_id>/order/', views.order_new, name='order_new'),
    path('o/<str:org_path>/<int:event_id>/order/add/', views.order_add, name='order_add'),
    path('o/<str:org_path>/<int:event_id>/order/confirmation/', views.order_thanks, name='order_thanks'),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms

class NumberOfTicketsToOrderForm(forms.Form):
   
    def __init__(self, *args, **kwargs):
        tickets = kwargs.pop('tickets')
        super(NumberOfTicketsToOrderForm, self).__init__(*args, **kwargs)

        for i, ticket in enumerate(tickets):
            self.fields['ticket_%s' % ticket.id] = forms.IntegerField(label=ticket.name, required=False, initial=0)

class NumberOfExtrasToOrderForm(forms.Form):
   
    def __init__(self, *args, **kwargs):
        extras = kwargs.pop('extras')
        super(NumberOfExtrasToOrderForm, self).__init__(*args, **kwargs)

        for i, extra in enumerate(extras):
            self.fields['extra_%s' % extra.id] = forms.IntegerField(label=extra.name, required=False, initial=0)

frontend/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from users.forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from datetime import datetime
from django.db.models import Sum, Count

from users.models import User
from backend.models import *
from frontend.forms import *
from frontend.logic.general import *
from frontend.logic.order import *

def index(request):
    context = {}
    return render(request, 'frontend/index.html', context)

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('frontend:login')
    template_name = 'frontend/signup.html'

def org(request, org_path):
    event_user = get_event_user_from_org_path(org_path)
    all_events_list = Event.objects.filter(user_id=event_user.id).order_by('date_start')
    context = {
        'all_events_list': all_events_list,
        'event_user': event_user,
    }
    print (all_events_list)
    return render(request, 'frontend/org.html', context)

def event(request, org_path, event_id):
    event_user = get_event_user_from_org_path(org_path)
    event = get_object_or_404(Event, pk=event_id)

    TODAY = datetime.today()

    all_tickets_list = Ticket.objects.filter(event_id=event.id, is_hidden=False, for_sale_date_start__lte=TODAY, for_sale_date_end__gte=TODAY, ticket_type=Ticket.TicketType.TICKET).order_by('for_sale_date_end')
    all_extras_list = Ticket.objects.filter(event_id=event.id, is_hidden=False, for_sale_date_start__lte=TODAY, for_sale_date_end__gte=TODAY, ticket_type=Ticket.TicketType.EXTRA).order_by('for_sale_date_end')

    form = NumberOfTicketsToOrderForm(tickets=all_tickets_list)
    form_extra = NumberOfExtrasToOrderForm(extras=all_extras_list)

    context = {
        'event': event,
        'event_user': event_user,
        'all_tickets_list': all_tickets_list,
        'all_extras_list': all_extras_list,
        'form': form,
        'form_extra': form_extra,
    }
    return render(request, 'frontend/event.html', context)


def order_new(request, org_path, event_id):
    # checks if any tickets or add-ons were selected. If not, doesn't let
    # the user load the checkout page (order_new)
    ids = get_list_of_ticket_ids_quantity(request)
    if not ids:
        print("in here")
        return HttpResponseRedirect(reverse('frontend:event', args=(org_path, event_id)))
    
    event_user = get_event_user_from_org_path(org_path)
    event = get_object_or_404(Event, pk=event_id)

    session_key = request.session.session_key

    if not request.session.exists(session_key):
        request.session.create()
        session_key = request.session.session_key

    if request.method == 'POST':
        clear_cart(session_key)

    save_ids_and_quantities_to_cart(session_key, ids)

    all_cart_list = get_cart(session_key)

    ticket_forms, ticket_prefixes, ticket_list = get_ticket_forms_prefixes_and_list(ids, event_id)

    order_form = OrderForm(prefix="order")

    total_price = get_cart_total_price(all_cart_list)

    context = {
        'event': event,
        'event_user': event_user,
        'order_form': order_form,
        'ticket_forms': ticket_forms,
        'ticket_prefixes': ticket_prefixes,
        'all_cart_list': all_cart_list,
        'ticket_list': ticket_list,
        'total_price': total_price,
    }
    return render(request, 'frontend/order_new.html', context)


@require_http_methods(["POST"])
def order_add(request, org_path, event_id):
    event_user = get_event_user_from_org_path(org_path)
    event = get_object_or_404(Event, pk=event_id)

    all_cart_list = get_cart(request.session.session_key)

    order_form = OrderForm(request.POST, prefix="order")

    cart_prefixes = get_cart_prefixes(all_cart_list)

    ticket_forms = list()

    prefixes = request.POST.get('ticket_prefixes').split(',')

    print(str(prefixes) + "\t" + str(cart_prefixes))

    # must be sorted, or the following if statement might fail
    cart_prefixes.sort()
    prefixes.sort()

    # check if the data from POST matches the data from the database
    if cart_prefixes == prefixes:
    
        for i in prefixes:
            ticket_forms.append(TicketOrderForm(request.POST, prefix=i))

        if order_form.is_valid() and are_tickets_valid(ticket_forms):
            order = order_form.save(commit=False)

            order.order_total = get_cart_total_price(all_cart_list)
            order.status = Order.Status.COMPLETE
            order.event = event

            order.save()

            # saves the tickets and the info from the form
            for form in ticket_forms:
                form = form.save(commit=False)
                form.order = order
                form.status = TicketOrder.Status.COMPLETE
                form.save()
            
            # saves the extras/add ons
            for cart in all_cart_list:
                if cart.ticket.ticket_type == Ticket.TicketType.EXTRA:
                    for q in range(0, cart.quantity):
                        TicketOrder.objects.create(ticket=cart.ticket, status=TicketOrder.Status.COMPLETE, order=order)

            clear_cart(request.session.session_key)
            save_order_id(request, order.id)

            return HttpResponseRedirect(reverse('frontend:order_thanks', args=(event_user.org_identifier, event.id)))

        else:
            clear_cart(request.session.session_key)
            context = {
                'event': event,
                'event_user': event_user,
                'order_form': order_form,
                'ticket_forms': ticket_forms,
                'all_cart_list': all_cart_list
            }
            return render(request, 'frontend/order_new.html', context)
    else:
        all_tickets_list = Ticket.objects.filter(event_id=event.id, is_hidden=False).order_by('name')
        form = NumberOfTicketsToOrderForm(tickets=all_tickets_list)
        context = {
            'event': event,
            'event_user': event_user,
            'all_tickets_list': all_tickets_list,
            'form': form,

        }
        messages.add_message(request, messages.ERROR, 'Something went wrong. Please try again.')
        return HttpResponseRedirect(reverse('frontend:event', args=(event_user.org_identifier, event.id)))

def order_thanks(request, org_path, event_id):
    order_id = get_order_id(request)

    event_user = get_event_user_from_org_path(org_path)
    event = get_object_or_404(Event, pk=event_id)
    order = get_object_or_404(Order, pk=order_id)
    count = TicketOrder.objects.filter(order__id=order_id)  \
        .values('ticket')                                   \
        .annotate(Count('ticket'))                          \
        .values('ticket', 'ticket__count', 'ticket__name')

    context = {
        'event': event,
        'event_user': event_user,
        'order': order,
        'count': count,
    }
    return render(request, 'frontend/order_thanks.html', context)

frontend/templates/frontend/event.html
{% extends 'base_frontend.html' %}

{% load frontend_extras %}

{% block title %}{{ event.name }}{% endblock %}

{% block body_class%}{%if event.banner%}has-banner {%endif%}has-aside {% endblock %}

{% block content_class%}event {% endblock %}

{% block banner %}
<div id="banner_image" class="banner">
    {% if event.banner %}
        <img class="drop-shadow" src="{{ event.banner.url }}">
    {% endif %}
</div>
{% endblock %}

{% block content %}
    <h1>{{ event.name }}</h1>

    <p>{{ event.description }}</p>

    {% if all_tickets_list or all_extras_list%}
        <form method="post" action="{% url 'frontend:order_new' event_user.org_identifier event.id %}">
    {% endif %}

    {% if all_tickets_list %}
        <h2>Tickets</h2>

        {% for form, ticket in form|zip:all_tickets_list %}
        <div class="item ticket box">
            <p><strong>{{ ticket.name }}</strong> &ndash; $ {{ ticket.price }}</p>
            <p class="ticket-sales-end">Sales End: {{ ticket.for_sale_date_end }}</p>
            <div class="flex-right">{{ form }}</div>
            <p class="ticket-description">{{ ticket.description }}</p>
        </div>
        {% endfor %}
    {% endif %}

    {% if all_extras_list %}
        <h2>Add Ons</h2>

        {% for form_extra, extra in form_extra|zip:all_extras_list %}
        <div class="item extra box">
            <p><strong>{{ extra.name }}</strong> &ndash; $ {{ extra.price }}</p>
            <p class="extra-sales-end">Sales End: {{ extra.for_sale_date_end }}</p>
            <div class="flex-right">{{ form_extra }}</div>
            <p class="extra-description">{{ extra.description }}</p>
        </div>
        {% endfor %}
    {% endif %}

    {% if all_tickets_list or all_extras_list%}
        <input type="submit" value="Checkout">
        {% csrf_token %}
        </form>
    {% endif %}

    {% if not all_tickets_list and not all_extras_list%}
        <p>No tickets are available.</p>
    {% endif %}

{% endblock %}

{% block aside %}
    <p><strong>Venue</strong>: {{ event.venue_name }}</p>
    <p><strong>Address</strong>: {{ event.venue_address }}</p>
    <p><strong>Starts</strong>: {{ event.date_start }}</p>
    <p><strong>Ends</strong>: {{ event.date_end }}</p>
{% endblock %}

frontend/templates/frontend/index.html
{% extends 'base_homepage.html' %}
{% load static %}


{% block hero %}
    <div class="text-logo">Eventori</div>
    <div id="tagline"><span class="text"><noscript>The simple event ticket application.</noscript></span><div id="cursor"></div></div>
{% endblock %}

{% block content_one_image %}
<img src="{% static 'frontend/homepage_images/event.png' %}">
{% endblock %}


{% block content_one_text %}
<h2>Create Events</h2>
<p>Create a new event quickly.</p>

{% endblock %}


{% block content_two_image %}
<img src="{% static 'frontend/homepage_images/attendees.png' %}">
{% endblock %}


{% block content_two_text %}
<h2>View Attendees</h2>
<p>View a list of attendees, and download the list to a .CSV file.</p>
{% endblock %}


{% block content_three_image %}
<img src="{% static 'frontend/homepage_images/ticket_stats.png' %}">
{% endblock %}


{% block content_three_text %}
<h2>Event Stats</h2>
<p>View the past 14 days of ticket sales, and download the ticket sale stats to a .CSV file.</p>
{% endblock %}


{% block content_form %}<p>form content will go here</p>{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'frontend/index.js' %}"></script>
{% endblock %}

frontend/templates/frontend/order_new.html
{% extends 'base_frontend.html' %}
{% load static %}

{% load frontend_extras %}

{% block title %}{{ event.name }} &dash; Checkout{% endblock %}

{% block body_class%}has-aside{% endblock%}

{% block content %}

<h1>{{ event.name }} &dash; Checkout</h1>

<form id="order_form" method="post" action="{% url 'frontend:order_add' event_user.org_identifier event.id %}">
    <h2 class="heading-name">Ticket Buyer Information</h2>
    <table cellpadding="0" data-number="0">{{ order_form.as_table }}</table>

    <h2>Ticket Information</h2>

    {% if ticket_forms %}

        {% for form, cart in ticket_forms|zip:ticket_list %}
            <h3 class="heading-name">#{{ forloop.counter }} &ndash; {{ cart.name }}</h3>
            <div class="copy-form"></div>
            <table cellpadding="0" data-number="{{ forloop.counter }}">{{ form.as_table }}</table>
        {% endfor %}

    {% endif %}

   <input type="hidden" name="ticket_prefixes" value="{{ ticket_prefixes }}" id="ticket_prefixes">

    <input type="submit" value="Purchase">
    {% csrf_token %}
</form>

{% endblock %}

{% block aside %}
    <h2>Items in Cart:</h2>
    <ul class="cart">
    {% for cart in all_cart_list %}
        <li>{{ cart.quantity }} x {{ cart.ticket.name }}</li>
    {% endfor %}
    </ul>
    <p>Total: ${{ total_price }}</p>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'frontend/order_form.js' %}"></script>
{% endblock %}

frontend/templates/frontend/order_thanks.html
{% extends 'base_frontend.html' %}

{% load frontend_extras %}

{% block title %}Order Confirmation &dash; {{ event.name }} {% endblock %}

{% block body_class%}{% endblock%}

{% block content %}

<h1>Thanks for Your Order!</h1>

<div>
    <h2>Items in your order:</h2>
    <ul>
    {% for item in count %}
        <li>{{ item.ticket__count }} x {{ item.ticket__name }}</li>
    {% endfor %}
    </ul>
    <p>Total: ${{ order.order_total }}</p>
</div>
<br>
<a class="button" href="{% url 'frontend:event' event_user.org_identifier event.id %}">Back to event page</a>


{% endblock %}

frontend/templates/frontend/org.html
{% extends 'base_frontend.html' %}

{% block title %}Events by {{ event_user.org_name }}{% endblock %}
{% block content %}

<h1>Events by {{ event_user.org_name }}</h1>

{% if all_events_list %}
    {% for event in all_events_list %}
        <div class="event">
            <span><strong>{{ event.name }}</strong></span>
            <div>Start Date: {{ event.date_start }}</div>
            <div>End Date: {{ event.date_end }}</div>
            <div>Category: {{ event.category }}</div>
            <ul class="links">
                <li class="view"><a href="{% url 'frontend:event' event_user.org_identifier event.id %}">View</a></li>
            </ul>
        </div>
        <br>
    {% endfor %}
{% else %}
    <p>No events are available.</p>
{% endif %}

{% endblock %}

frontend/templates/frontend/signup.html
{% extends 'base_frontend.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}