backend/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib import admin

from . import views

app_name = 'backend'
urlpatterns = [
    path('', views.admin, name='admin'),

    path('categories/', views.category_list, name='category_list'),
    path('categories/new/', views.category_new, name='category_new'),
    path('categories/add/', views.category_add, name='category_add'),
    path('categories/<int:category_id>/', views.category_details, name='category_details'),
    path('categories/<int:category_id>/edit/', views.category_edit, name='category_edit'),
    path('categories/<int:category_id>/delete/', views.category_delete, name='category_delete'),

    path('e/', views.event_list, name='event_list'),
    path('e/new/', views.event_new, name='event_new'),
    path('e/add/', views.event_add, name='event_add'),
    path('e/<int:event_id>/dashboard', views.event_dashboard, name='event_dashboard'),
    path('e/<int:event_id>/publish', views.event_publish_button, name='event_publish_button'),
    path('e/<int:event_id>/', views.event_details, name='event_details'),
    path('e/<int:event_id>/edit/', views.event_edit, name='event_edit'),
    path('e/<int:event_id>/delete/', views.event_delete, name='event_delete'),

    path('e/<int:event_id>/t/', views.ticket_list, name='ticket_list'),
    path('e/<int:event_id>/t/new/', views.ticket_new, name='ticket_new'),
    path('e/<int:event_id>/t/add/', views.ticket_add, name='ticket_add'),
    path('e/<int:event_id>/t/<int:ticket_id>/', views.ticket_details, name='ticket_details'),
    path('e/<int:event_id>/t/<int:ticket_id>/edit/', views.ticket_edit, name='ticket_edit'),
    path('e/<int:event_id>/t/<int:ticket_id>/delete/', views.ticket_delete, name='ticket_delete'),

    path('e/<int:event_id>/attendees/', views.attendee_list, name='attendee_list'),
    path('e/<int:event_id>/attendees/download/', views.attendee_download, name='attendee_download'),
    path('e/<int:event_id>/attendees/download-addons/', views.attendee_download_addon, name='attendee_download_addon'),
    path('e/<int:event_id>/orders/', views.order_list, name='order_list'),
    path('e/<int:event_id>/orders/download/', views.order_download, name='order_download'),
    path('e/<int:event_id>/stats/', views.stat_show, name='stat_show'),
    path('e/<int:event_id>/stats/location-download', views.stat_location_download, name='stat_location_download'),
    path('e/<int:event_id>/stats/date-ticket-download', views.stat_date_ticket_download, name='stat_date_ticket_download'),
    path('e/<int:event_id>/stats/date-addon-download', views.stat_date_addon_download, name='stat_date_addon_download'),
    path('e/<int:event_id>/stats/revenue-download', views.stat_revenue_download, name='stat_revenue_download'),
]

event_ticket_py/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frontend.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', include('backend.urls')),
    path('django-admin/', admin.site.urls), # comment this out when doing custom user migrations the first time
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib import admin

from . import views
from frontend.views import SignUpView

app_name = 'frontend'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('o/<str:org_path>/', views.org, name='org'),
    path('o/<str:org_path>/<int:event_id>/', views.event, name='event'),
    path('o/<str:org_path>/<int:event_id>/order/', views.order_new, name='order_new'),
    path('o/<str:org_path>/<int:event_id>/order/add/', views.order_add, name='order_add'),
    path('o/<str:org_path>/<int:event_id>/order/confirmation/', views.order_thanks, name='order_thanks'),
]

templates/base_backend.html
{% load i18n %}
{% load static %}
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %} &vert; Eventori</title>
    <link href="{% static 'frontend/reset.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'frontend/general.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'backend/main.scss' %}" rel="stylesheet" type="text/css" />
</head>

<body class="{% block body_class %}{% endblock %}">
    <header class="grid">
        {% block header %}
            {% include 'header.html' %}
        {% endblock %}
    </header>

    <nav id="nav_main">
        {% block navigation_main %}
            {% include 'nav_main.html' %}
        {% endblock %}
    </nav>

    {% block navigation_secondary %}
    {% endblock %}

    <div id="content">
        {% include 'messages.html' %}
        {% block content %}{% endblock %}
    </div>

    <footer>
        {% block footer %}
        {% include 'footer.html' %}
        {% endblock %}
    </footer>
</body>

{% block scripts %}{% endblock %}
<script type="text/javascript" src="{% static 'frontend/general.js' %}"></script>
</html>

templates/base_frontend.html
{% load i18n %}
{% load static %}
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %} &vert; Eventori</title>
    <link href="{% static 'frontend/reset.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'frontend/general.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'frontend/main.scss' %}" rel="stylesheet" type="text/css" />
</head>

<body class="{% block body_class %}{% endblock %}">
    <header class="grid header">
        {% block header %}
            {% include 'header.html' %}
        {% endblock %}
    </header>

    {% block banner %}{% endblock %}

    <div class="{% block content_class %}{% endblock %} main">
        <div class="box inner">
        {% include 'messages.html' %}
        {% block content %}{% endblock %}
        </div>
    </div>

    <div class="aside">
        <div class="box inner">
            {% block aside %}
            {% endblock %}
        </div>
    </div>

    <footer class="footer">
        {% block footer %}
        {% include 'footer.html' %}
        {% endblock %}
    </footer>
</body>

{% block scripts %}{% endblock %}
<script type="text/javascript" src="{% static 'frontend/general.js' %}"></script>

</html>

templates/base_homepage.html
{% load i18n %}
{% load static %}
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Eventori</title>
    <link href="{% static 'frontend/reset.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'frontend/general.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'frontend/main.scss' %}" rel="stylesheet" type="text/css" />
</head>

<body class="homepage{% block body_class %}{% endblock %}">

    <header class="grid header">
        {% block header %}
            {% include 'header.html' %}
        {% endblock %}
    </header>

    <div class="wrapper">

    <div class="background-hero">
        <div class="hero">
            {% block hero %}{% endblock %}
            {% include 'messages.html' %}
        </div>
    </div>

    <div class="background-1">
        <div class="content-one-image">
            {% block content_one_image %}{% endblock %}
        </div>
        <div class="content-one-text">
            {% block content_one_text %}{% endblock %}
        </div>
    </div>

    <div class="background-2">
        <div class="content-two-image">
            {% block content_two_image %}{% endblock %}
        </div>
        <div class="content-two-text">
            {% block content_two_text %}{% endblock %}
        </div>
    </div>

    <div class="background-3">
        <div class="content-three-image">
            {% block content_three_image %}{% endblock %}
        </div>
        <div class="content-three-text">
            {% block content_three_text %}{% endblock %}
        </div>
    </div>

    <div class="background-form">
        <div class="contact-form">
            {% block content_form %}{% endblock %}
        </div>
    </div>

    <footer class="footer">
        {% block footer %}
        {% include 'footer.html' %}
        {% endblock %}
    </footer>

    </div>

</body>

{% block scripts %}{% endblock %}
<script type="text/javascript" src="{% static 'frontend/general.js' %}"></script>

</html>

templates/footer.html
<div>Copyright &copy; Michelle Beaulé</div>

templates/header.html
{% load i18n %}
{% load static %}

<div class="flex-left"><a href="{% url 'frontend:index' %}"><img class="logo" src="{% static 'frontend/logo.png' %}"></a></div>

{% if user.is_authenticated %}
<p class="flex-right">
    <span><a href="{% url 'backend:admin' %}">Admin</a></span>
    <span>{{ user.email }} (<a href="{% url 'frontend:logout' %}">Log out</a>)</span></p>
{% else %}
<span><p class="flex-right"><a href="{% url 'frontend:login' %}">Login</a> | <a href="{% url 'frontend:signup' %}">Signup</a></p></span>
{% endif %}

templates/messages.html
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}{{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

templates/nav_events.html
<nav id="nav_secondary">
    <ul>
        <li><a href="{% url 'backend:event_new' %}">New Event</a></li>
        <li><hr></li>
        <li><a href="{% url 'backend:event_dashboard' event_id %}">Dashboard</a></li>
        <li><a href="{% url 'backend:event_details' event_id %}">Edit Event</a></li>
        <li><a href="{% url 'backend:ticket_list' event_id %}">Tickets</a></li>
        <li><a href="{% url 'backend:attendee_list' event_id %}">Attendees</a></li>
        <li><a href="{% url 'backend:order_list' event_id %}">Orders</a></li>
        <li><a href="{% url 'backend:stat_show' event_id %}">Stats</a></li>
        <li><hr></li>
        <li><a href="{% url 'frontend:event' org_path=user.org_identifier event_id=event.id %}" target="_blank">View</a></li>
    </ul>
</nav>

templates/nav_main.html
<div>

<ul>
<li><a href="{% url 'backend:admin' %}">Admin</a></li>
<li><a href="{% url 'backend:event_list' %}">Events</a></li>
<li><a href="{% url 'backend:category_list' %}">Categories</a></li>
</ul>

</div>